language: python
python: 3.5
sudo: false

env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py35-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django19

install:
    - pip install tox

script:
  - tox -e $TOX_ENV
